<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import keras
from keras.datasets import mnist
import numpy as np
import cv2
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:
image=cv2.imread("mnist_zero.png")

In [11]:
image.shape

(28, 28, 3)

In [12]:
print(image)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [13]:
from tensorflow.keras.preprocessing.image import img_to_array

In [18]:
n=img_to_array(image)

In [15]:
len(n)

28

In [16]:
n.shape

(28, 28, 3)

In [9]:
image

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [36]:
def f(a, L=[]):
    L.insert(0,a)
    return L
print(f(1))
print(f(2))
print(f(3))

[1]
[2, 1]
[3, 2, 1]


In [32]:
def question_coins_2(n0, n1, n2):
  actual = {0: n0, 1: n1, 2: n2}
  max_val = sum(k*v for k,v in actual.items())
  divisible_values = [i for i in range(max_val + 1) if i % 3 == 0]
  seq = [0]*n0 + [1]*n1 + [2]*n2
  sum_of_all_combinations = 0
  for val in divisible_values:
    res = subset_sum(seq, val)
    for r in res:
      req_actual = actual.keys() & r.keys()
      prod = 1
      for key in req_actual:
        prod *= nCr(actual[key], r[key])
      sum_of_all_combinations += prod
  return sum_of_all_combinations / pow(2, (n0 + n1 + n2))

In [31]:
def subset_sum(seq, target, partial=[], combs=None):
  if combs is None:
    combs = []
  s = sum(partial)
  # check if the partial sum is equals to target
  if s == target:
    count_ele = dict(zip(list(partial),[list(partial).count(i) for i in list(partial)]))
    combs.append(count_ele) if count_ele not in combs else combs
  if s > target:
    return  # if we reach the number why bother to continue
  for i in range(len(seq)):
    n = seq[i]
    remaining = seq[i+1:]
    subset_sum(remaining, target, partial + [n], combs=combs)
  return combs

In [34]:
from math import factorial as fact
def nCr(n, r):
  return fact(n) // fact(r) // fact(n-r)
print(question_coins_2(1,1,1))

0.5
